export const DEFAULT_API_KEY = '2b3a01370e91b77df6531635dbf97cd2'
export const DEFAULT_LANG = 'en'
export const DEFAULT_UNITS = 'metric'
export const DEFAULT_LOCATION = 'Warsaw,pl'
export const BASE_URL = 'http://api.openweathermap.org/data/2.5/forecast'
